package pkgfinal;

import pkgfinal.FrameProject;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;


public class LoginFrame extends javax.swing.JFrame {
    private static JLayeredPane layers;
    private static JLabel WELCOME;
    private static JLabel diskripsi;
    
    public LoginFrame() {
        //Membuat frame login dengan nama fram Login Swalayan Amanah
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setBounds(500, 300, 500, 256);
        setSize(500, 500);
        setTitle("Login Swalayan Amanah");
        
        //Mengatur background, batas, dan penemoatan frame
        JPanel panel = new JPanel();
        panel.setBackground(new Color(204, 204, 255));
        panel.setBorder(new EmptyBorder(10, 10, 10, 10));
        panel.setLayout(new BorderLayout(0,0));
        setContentPane(panel); //menyeting agar komponen di GUI yang telah dibuat dapat tampil di frame utama
        
        layers = new JLayeredPane(); //memungkinkan untuk menumpuk komponen lain pada panel yang telat dibuat
        panel.add(layers, BorderLayout.CENTER);
        
        //membuat tulisan Selamat datang di frame Login
        WELCOME = new JLabel("Selamat Datang Admin Kasir!");
        WELCOME.setBounds(60, 40, 500, 60);
        WELCOME.setBorder(new EmptyBorder(0, 0, 0, 0));
        WELCOME.setFont(new Font("serif", Font.CENTER_BASELINE, 25));
        layers.add(WELCOME);
        
        //membuat tulisan diskripsi
        diskripsi = new JLabel("Tersedia berbagai macam kebutuhan rumah");
        diskripsi.setBounds(40, 120, 500  , 50);
        diskripsi.setFont(new Font("Arial Black", Font.ROMAN_BASELINE, 16));
        layers.add(diskripsi);
        
        //membuat label username
        JLabel username = new JLabel("Username : ");
        username.setBounds(130, 200, 100, 20);
        username.setFont(new Font("Arial Black", Font.ROMAN_BASELINE, 15));
        layers.add(username);
        
        //membuat label password
        JLabel password = new JLabel("Password : ");
        password.setBounds(130, 230, 100, 20);
        password.setFont(new Font("Arial Black", Font.ROMAN_BASELINE, 15));
        layers.add(password);
        
        //membuat kotak untuk memasukkan username
        JTextField textField = new JTextField();
        textField.setBounds(230, 200, 100, 30);
        layers.add(textField);
        
        //membuat kotak untuk memasukkan password
        JTextField passwordField = new JPasswordField();
        passwordField.setBounds(230, 230, 100, 30);
        layers.add(passwordField);
        
        //setting pemberitahuan ketika ternyata admin salah memasukkan username atau password
        JLabel sorry = new JLabel();
        sorry.setForeground(Color.BLACK);
        sorry.setFont(new Font("Tahoma", Font.PLAIN, 15));
        sorry.setHorizontalAlignment(SwingConstants.RIGHT);
        sorry.setBounds(30, 260, 390, 20);
        layers.add(sorry);

        //membuat buuton lgin
        JButton ButtonAwal = new JButton("Login");
        ButtonAwal.setLocation(180, 300);
        ButtonAwal.setSize(100, 50);
        layers.add(ButtonAwal);
        
        //membuat action pada button login dimana ketika username dan password benar dan kemudian
        //admin memencet tombol Login maka akan muncul frame kasir, namun jika salah akan muncul pemberitahuan
        ButtonAwal.addActionListener(new ActionListener() {  
            public void actionPerformed(ActionEvent e) {
                if (textField.getText().equals("admin") && passwordField.getText().equals("admin")) {
                    //memunculkan frame kasir jika benar
                    FrameProject frame = new FrameProject();
                    frame.setVisible(true);
                    frame.pack();
                    frame.setLocationRelativeTo(null);
                    frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
                }
                else{
                    //pemberitahuan jika salah memasukkan password atau username
                    sorry.setText("The username or password you entered is incorrect");
                }
            }
        });
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setText("SELAMAT DATANG!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
